global:
  keycloakBaseUrl: https://keycloak.openg2p.net
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'
  RBGTasksHostname: registry-bg-tasks.openg2p.sandbox.net

openg2p-registry-celery-beat-producers:
  enabled: true
  image:
    registry: docker.io
    repository: openg2p/openg2p-registry-celery-beat-producers
    tag: '1.1.0'
  common:
    enabled: false
  redis:
    enabled: false
  envVars:
    REGISTRY_CELERY_BEAT_DB_DBNAME: socialregistrydb
    REGISTRY_CELERY_BEAT_DB_PORT: 5432
    REGISTRY_CELERY_BEAT_DB_USERNAME: postgres
    REGISTRY_CELERY_BEAT_DB_HOSTNAME: 'social-registry-postgresql'
    REGISTRY_CELERY_BEAT_CELERY_BROKER_URL: redis://{{ .Release.Name }}-redis-master:6379/0
    REGISTRY_CELERY_BEAT_CELERY_BACKEND_URL: redis://{{ .Release.Name }}-redis-master:6379/0
    REGISTRY_CELERY_BEAT_WORKER_TYPE_MAX_ATTEMPTS: '{"max_id_generation_request_attempts": 4, "max_id_generation_update_attempts": 4}'


  envVarsFrom:
    REGISTRY_CELERY_BEAT_DB_PASSWORD:
      secretKeyRef:
        name: 'social-registry-postgresql'
        key: postgres-password

openg2p-registry-celery-workers:
  enabled: true
  image:
    registry: docker.io
    repository: openg2p/openg2p-registry-celery-workers
    tag: '1.1.0'
  common:
    enabled: false
  redis:
    enabled: false
  envVars:
    REGISTRY_CELERY_WORKERS_DB_DBNAME: socialregistrydb
    REGISTRY_CELERY_WORKERS_DB_USERNAME: postgres
    REGISTRY_CELERY_WORKERS_DB_HOSTNAME: 'social-registry-postgresql'
    REGISTRY_CELERY_WORKERS_DB_PORT: 5432
    REGISTRY_CELERY_WORKERS_CELERY_BROKER_URL: redis://{{ .Release.Name }}-redis-master:6379/0
    REGISTRY_CELERY_WORKERS_CELERY_BACKEND_URL: redis://{{ .Release.Name }}-redis-master:6379/0
    REGISTRY_CELERY_WORKERS_AUTH_URL: '{{ tpl .Values.global.keycloakIssuerUrl $ }}/protocol/openid-connect/token'
    REGISTRY_CELERY_WORKERS_AUTH_CLIENT_ID: 'client-id'
    REGISTRY_CELERY_WORKERS_AUTH_CLIENT_SECRET: 'secret'
    REGISTRY_CELERY_WORKERS_AUTH_GRANT_TYPE: client_credentials
    REGISTRY_CELERY_WORKERS_MOSIP_GET_UIN_URL: https://idgenerator.dev.openg2p.net/v1/idgenerator/uin
    REGISTRY_CELERY_WORKERS_MOSIP_UPDATE_UIN_URL: https://idgenerator.dev.openg2p.net/v1/idgenerator/uin
    REGISTRY_CELERY_WORKERS_WORKER_TYPE_MAX_ATTEMPTS: '{"max_id_generation_request_attempts": 4, "max_id_generation_update_attempts": 4}'

  envVarsFrom:
    REGISTRY_CELERY_WORKERS_DB_PASSWORD:
      secretKeyRef:
        name: 'social-registry-postgresql'
        key: postgres-password

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

