apiVersion: v2
name: openg2p-sr-bg-tasks
description: A Helm chart for OpenG2P SR BG Tasks
type: application
version: 1.0.0-develop
appVersion: ""
dependencies:
- name: openg2p-sr-bg-tasks-celery-beat-producers
  version: 1.0.0-develop
  condition: openg2p-sr-bg-tasks-celery-beat-producers.enabled
- name: openg2p-sr-bg-tasks-celery-workers
  version: 1.0.0-develop
  condition: openg2p-sr-bg-tasks-celery-workers.enabled
keywords:
  - openg2p-sr-bg-tasks
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P-SR-BG-Tasks"

